# http://travis-ci.org/#!/graphite-project/carbon
language: python
python:
    - 2.7
    - pypy

env:
    - TOXENV=ci

install:
    - pip install -r requirements.txt
    - python setup.py install --prefix=$VIRTUAL_ENV --install-lib=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - pip install tox

script:
    - tox -e $TOXENV

sudo: false
